### PR TITLE
Integrate drdavella/tox-conda

### LINKED ISSUE #4: Request for collaboration
I have developed an independent implementation of [tox-conda](https://github.com/drdavella/tox-conda). It has been released on [pypi](https://pypi.org/project/tox-conda/) and is currently being used in production by [sunpy](https://sunpy.org/) and [asdf](https://github.com/spacetelescope/asdf). It is under consideration for adoption by [astropy](http://www.astropy.org/) as well.

I am hoping that you might be interested in bringing this package under `tox-dev`. It would certainly benefit from increased collaboration, and I think that there are a few changes that could be made to `tox` itself in order to better support this plugin.

### PR DESCRIPTION
**Pull request by drdavella**
This resolves #4. I'm sure that there will be lots of comments and lots of room for improvements, but it might be a good idea to merge this as-is before moving forward with other changes.

### CODE REVIEW

**Comment by drdavella** [comment]
I have been doing Windows testing on `travis` these days since it's so much faster. I wonder if we can just disable appveyor for this plugin?

**Comment by obestwalter** [comment]
Hi @drdavella - great that this is moving forward. I just sent you an invite into the org, so you have full access here regarding plugins.

I didn't know that Travis now supports Windows builds - that's great news. I am all for moving away from appveyor as this does not support org access to the Travis backend. I reckon appveyor is on the way out anyway and to be superceded by azure pipelines.

I am putting detox to rest atm and after that I am definitely also interested to figure out how this all works and help here if I can.

**Comment by obestwalter** [comment]
o.k. merged and add a few quick issues mainly as reminder for myself what needs to be sorted.

Welcome onboard @drdavella :smile:

**Comment by drdavella** [comment]
Thank you!

**Comment by drdavella** [comment]
Is there any chance you could make me an admin of this repo temporarily? That would allow me to try to move an issue from my original repo (there are some comments on there that would be good to preserve).

**Comment by obestwalter** [comment]
Hey aren't you yet? I thought that would be sorted by making you a plugin maintainer. I'll have a look.

**Comment by obestwalter** [comment]
@drdavella You must have gotten an invite, maybe it's in your spam folder?

You will be admin for plugin development then.

**Comment by drdavella** [comment]
@obestwalter I can't find the invitation email anywhere. Is there any chance you can try to resend it?

**Comment by obestwalter** [comment]
I just did - any luck this time?

**Comment by obestwalter** [comment]
You should also be able to go directly to the tox-dev org and accept it there - at least that's what the invite overview suggests:

scrot

**Comment by drdavella** [comment]
I still didn't see an email, but that worked for me. Oh well.

And it looks like I still can't move the issue across organizations, unfortunately 😢.

**Comment by obestwalter** [comment]
ah - the repo wasn't configured properly for that yet - now try again please :)

**Comment by drdavella** [comment]
Still doesn't work... I think this might reflect the fact that the feature is still in "beta" mode, unfortunately.

**Comment by obestwalter** [comment]
But you are admin of this repo now, are you?

I moved over some issues from tox to detox recently, but I think that was even before the inbuilt functionality with the help of a browser extension. https://chrome.google.com/webstore/detail/kamino/. I usually use firefox and intalled chrome just to be able to do that - that did the job.

**Pull request merged**
