### PR TITLE
[WIP] initial conda support

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by obestwalter** [comment]
Hi @kalefranz great to see this start growing :+1:

The failure in Travis is because tox needs to be installed for the plugin to work (this is why it can't import _pytestplugin). This is now commented out in setup.py and therefore it fails.

On Appveyor it tries to compile a dependency, ideally there would be a wheel for it, that can be installed instead.

**Comment by kalefranz** [comment]
Yeah consider this PR work in progress until I get the CI issues worked out.  Still need some more time on it.

**Comment by obestwalter** [comment]
Please don't forget to add yourself to the authors.

**Comment by kalefranz** [comment]
Still WIP because I've been working on https://github.com/conda/conda/pull/7291.  I think use of this flag is necessary for the best tox + conda experience.  So tox-conda will require a minimum of conda 4.6.

**Comment by kalefranz** [comment]
Want to confirm that this PR isn't abandoned.  Not at all.  conda/conda#7291 has been merged into conda's master branch.  And https://github.com/conda/conda/pull/7320 is using the same code we started here for collecting environment variables during environment activation, and it's easier for me to get all the logic and edge cases (or as many as possible) right on the conda side first.

I'm targeting this PR, and tox-conda in general, to be compatible with conda 4.6 and onward.

**Comment by kalefranz** [comment]
> docs on `conda-build` are a bit hit and miss

Docs on conda proper are honestly even worse right now.  We know we have a problem. Something we're acutely aware of and highly keen on fixing.

> From what I can see, you're installing `conda` into an existing (regular) Python environment.

Not really.  We're assuming that conda is on the system somewhere, and the process running tox has been properly initialized for conda support (e.g. the appropriate lines in `~/.bashrc`, provided in conda 4.6 via `conda init`).  We're creating new conda environments with python in them in the `.tox` directory, not installing conda into an existing python environment.

> or should it start from Miniconda, install the conda (or conda-forge) tox package and go from there?

So far, this PR doesn't `import conda`.  It just assumes that `conda` is on `PATH`, or more accurately the process running tox has been properly initialized for conda support, as discussed before.  We may get to the point where we do want this plugin to `import conda`, but it hasn't been necessary yet.  If that's the case though, `conda` and `tox` will obviously have to  (err, ideally) live together in the same `site-packages` directory.

> * Translate dependency matrix to conda
> * For each entry:
>   - Create an empty environment
>   - Pin fixed requirements
>   - Install requirements
>   - Test

I don't see any obvious problems with that workflow.  I guess that's basically what I had in mind too.

**Comment by TiemenSch** [comment]
Good to know the docs issue is acknowledged!

How can I be of best use? I'd love to debug some builds, but I'm kind of in the dark here. I'll be reading into tox and pluggy tonight. 

Otherwise, I'm willing to help on the doc side of things. If you describe the quick and dirty, I'd gladly help to elaborate a little.

**Comment by TiemenSch** [comment]
So I read up on pluggy last night and this stuff is great! It took a while to understand how tox gets installed on the command line (not used to that) and what it runs. I created a conda env to debug with tox installed (by conda) and an editable install with pip (so the plugin gets registered). 

As stated in some other places ([fizzylogic](http://fizzylogic.nl/2017/11/01/how-to-setup-tox-on-windows-with-anaconda/), [fauskanger](https://github.com/fauskanger/tox_with_conda)) before, to get tox detecting any conda python quickly, it's easiest to just create a symlink to your environment. So I symlinked C:\Python36 with a junction to point to my Miniconda3\envs\tox-env. I guess detecting conda installs is a little tricky. 

For me, personally, the easiest way to debug what is going on is creating a little script to run with my debugger:
**debug.py**
```python
import tox
tox.session.main("")
```
That way, it hits all breakpoints I setup in tox-conda :).

As far as testing goes, I guess we should just test the I/O of any hook we implement. Given sane input from tox, give correct output. 

Would you rather have me splitting the individual steps into issues or just work on this MR?

**Comment by drdavella** [comment]
Closing since this has been superseded by #5.

**Pull request closed without merging**
