### PR TITLE
Fix for windows not finding the good python.exe in conda env

### PR DESCRIPTION
**Pull request by rompom**
Pr for #26

### CODE REVIEW

**Comment by rompom** [comment]
@obestwalter , @gaborbernat any idea if/when the pr will be merged and released ?

**Comment by obestwalter** [comment]
I'll gladly merge it and release it, but with the fat caveat that I am not a user of this myself. Active users willing to help maintain this would be very welcome :bowing_man:

**Comment by smarie** [comment]
The failing tests on appveyor seem to be unrelated to the pr, it complains about `--timeout` not being recognized as a valid pytest arg:

```
py37 run-test: commands[0] | pytest --cov 'C:\projects\tox-conda\.tox\py37\Lib\site-packages/tox_conda' --cov-config 'C:\projects\tox-conda/tox.ini' --timeout 180 --junitxml 'C:\projects\tox-conda\.tox/.test.py37.xml' tests
ERROR: usage: pytest.EXE [options] [file_or_dir] [file_or_dir] [...]
pytest.EXE: error: unrecognized arguments: --timeout tests
  inifile: C:\projects\tox-conda\setup.cfg
  rootdir: C:\projects\tox-conda
ERROR: InvocationError for command 'C:\projects\tox-conda\.tox\py37\Scripts\pytest.EXE' --cov '.tox\py37\Lib\site-packages\tox_conda' --cov-config tox.ini --timeout 180 --junitxml 'C:\projects\tox-conda\.tox/.test.py37.xml' tests (exited with code 4)
```

**Comment by obestwalter** [comment]
ah - thanks for checking. That is fixed with #31 - so I'd say we merge this.

**Pull request merged**
