### PR TITLE
Fix #79 and #92

### LINKED ISSUE #79: Can't use conditional dependencies?
Trying to set conditional dependencies using tox with tox-conda causes an error when running tox.

Sample setup:
```
src/
    tox_conda_trial/
        __init__.py  <-- empty file
tests/
    test_example.py
pyproject.toml
setup.py
tox.ini
```
with:
- test_example.py
```python
import tox_conda_trial

def test_example():
    assert True
```
- pyproject.toml
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```
- setup.py
```python
from setuptools import find_packages, setup

setup(
    name="tox_conda_trial",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
)
```
- tox.ini
```
[tox]
isolated_build = true
requires = tox-conda
envlist =
    py{37, 38}-cr33

[testenv]
deps =
    pytest
    cr33: cryptography>=3.3,<3.4
commands =
    pytest
```

Active conda env is python 3.7 with tox installed, but not tox-conda, cryptography, pytest. Output of `conda env export`:
```
name: tox-conda-trial-env
channels:
  - defaults
dependencies:
  - ca-certificates=2021.4.13=hecd8cb5_1
  - certifi=2020.12.5=py37hecd8cb5_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1k=h9ed2024_0
  - pip=21.0.1=py37hecd8cb5_0
  - python=3.7.10=h88f2d9e_0
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - sqlite=3.35.4=hce871da_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appdirs==1.4.4
    - distlib==0.3.1
    - filelock==3.0.12
    - importlib-metadata==4.0.1
    - packaging==20.9
    - pluggy==0.13.1
    - py==1.10.0
    - pyparsing==2.4.7
    - six==1.16.0
    - toml==0.10.2
    - tox==3.23.1
    - typing-extensions==3.10.0.0
    - virtualenv==20.4.6
    - zipp==3.4.1
prefix: /Users/nicholasiles/anaconda3/envs/tox-conda-trial-env
```

Output of `tox`:
```
.tox create: /Users/nicholasiles/tox-conda-trial/.tox/.tox
.tox installdeps: tox-conda, tox >= 3.23.1
.package create: /Users/nicholasiles/tox-conda-trial/.tox/.package
.package installdeps: setuptools, wheel
py37-cr33 create: /Users/nicholasiles/tox-conda-trial/.tox/py37-cr33
py37-cr33 installdeps: pytest, cryptography>=3.3,<3.4
ERROR: invocation failed (exit code 1), logfile: /Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/log/py37-cr33-1.log
================================================================================== log start ===================================================================================
/Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/.tmpnty7ihnq: line 3: 3.4: No such file or directory
ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['/Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/bin/python', '-m', 'pip', 'install', 'pytest', 'cryptography>=3.3,<3.4']' command failed.  (See above for error)

=================================================================================== log end ====================================================================================
ERROR: could not install deps [pytest, cryptography>=3.3,<3.4]; v = InvocationError("/Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/bin/python -m pip install pytest 'cryptography>=3.3,<3.4'", 1)
py38-cr33 create: /Users/nicholasiles/tox-conda-trial/.tox/py38-cr33
py38-cr33 installdeps: pytest, cryptography>=3.3,<3.4
ERROR: invocation failed (exit code 1), logfile: /Users/nicholasiles/tox-conda-trial/.tox/py38-cr33/log/py38-cr33-1.log
================================================================================== log start ===================================================================================
/Users/nicholasiles/tox-conda-trial/.tox/py38-cr33/.tmp3_uatwoj: line 3: 3.4: No such file or directory
ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['/Users/nicholasiles/tox-conda-trial/.tox/py38-cr33/bin/python', '-m', 'pip', 'install', 'pytest', 'cryptography>=3.3,<3.4']' command failed.  (See above for error)

=================================================================================== log end ====================================================================================
ERROR: could not install deps [pytest, cryptography>=3.3,<3.4]; v = InvocationError("/Users/nicholasiles/tox-conda-trial/.tox/py38-cr33/bin/python -m pip install pytest 'cryptography>=3.3,<3.4'", 1)
___________________________________________________________________________________ summary ____________________________________________________________________________________
ERROR:   py37-cr33: could not install deps [pytest, cryptography>=3.3,<3.4]; v = InvocationError("/Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/bin/python -m pip install pytest 'cryptography>=3.3,<3.4'", 1)
ERROR:   py38-cr33: could not install deps [pytest, cryptography>=3.3,<3.4]; v = InvocationError("/Users/nicholasiles/tox-conda-trial/.tox/py38-cr33/bin/python -m pip install pytest 'cryptography>=3.3,<3.4'", 1)
```

This command runs as expected when removing the `>=3.3,<3.4` condition on cryptography in tox.ini (no other changes):
```
.tox create: /Users/nicholasiles/tox-conda-trial/.tox/.tox
.tox installdeps: tox-conda, tox >= 3.23.1
.package create: /Users/nicholasiles/tox-conda-trial/.tox/.package
.package installdeps: setuptools, wheel
py37-cr33 create: /Users/nicholasiles/tox-conda-trial/.tox/py37-cr33
py37-cr33 installdeps: pytest, cryptography
py37-cr33 inst: /Users/nicholasiles/tox-conda-trial/.tox/.tmp/package/1/tox_conda_trial-0.0.0.tar.gz
py37-cr33 installed: attrs==21.2.0,certifi==2020.12.5,cffi==1.14.5,cryptography==3.4.7,importlib-metadata==4.0.1,iniconfig==1.1.1,packaging==20.9,pluggy==0.13.1,py==1.10.0,pycparser==2.20,pyparsing==2.4.7,pytest==6.2.4,toml==0.10.2,tox-conda-trial @ file:///Users/nicholasiles/tox-conda-trial/.tox/.tmp/package/1/tox_conda_trial-0.0.0.tar.gz,typing-extensions==3.10.0.0,zipp==3.4.1
py37-cr33 run-test-pre: PYTHONHASHSEED='3325570120'
py37-cr33 run-test: commands[0] | pytest
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py37-cr33/.pytest_cache
rootdir: /Users/nicholasiles/tox-conda-trial
collected 1 item

tests/test_example.py .                                                                                                                                                  [100%]

============================================================================== 1 passed in 0.01s ===============================================================================
py38-cr33 create: /Users/nicholasiles/tox-conda-trial/.tox/py38-cr33
py38-cr33 installdeps: pytest, cryptography
py38-cr33 inst: /Users/nicholasiles/tox-conda-trial/.tox/.tmp/package/1/tox_conda_trial-0.0.0.tar.gz
py38-cr33 installed: attrs==21.2.0,certifi==2020.12.5,cffi==1.14.5,cryptography==3.4.7,iniconfig==1.1.1,packaging==20.9,pluggy==0.13.1,py==1.10.0,pycparser==2.20,pyparsing==2.4.7,pytest==6.2.4,toml==0.10.2,tox-conda-trial @ file:///Users/nicholasiles/tox-conda-trial/.tox/.tmp/package/1/tox_conda_trial-0.0.0.tar.gz
py38-cr33 run-test-pre: PYTHONHASHSEED='3325570120'
py38-cr33 run-test: commands[0] | pytest
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.8.8, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38-cr33/.pytest_cache
rootdir: /Users/nicholasiles/tox-conda-trial
collected 1 item

tests/test_example.py .                                                                                                                                                  [100%]

============================================================================== 1 passed in 0.01s ===============================================================================
___________________________________________________________________________________ summary ____________________________________________________________________________________
  py37-cr33: commands succeeded
  py38-cr33: commands succeeded
  congratulations :)
```

Considering the contents of .tox/py37-cr33/log/py37-cr33-1.log:
```action: py37-cr33, msg: getenv
cwd: /Users/nicholasiles/tox-conda-trial
cmd: /Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/bin/python -m pip install pytest 'cryptography>=3.3,<3.4'
/Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/.tmpnty7ihnq: line 3: 3.4: No such file or directory
ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['/Users/nicholasiles/tox-conda-trial/.tox/py37-cr33/bin/python', '-m', 'pip', 'install', 'pytest', 'cryptography>=3.3,<3.4']' command failed.  (See above for error)
```
and that the failing version creates a file named `=3.3,`, it appears that the quotation marks required around `'cryptography>=3.3,<3.4'` are not being escaped properly when passing to the `conda run` subprocess, and effectively we end up trying to run `python -m pip install pytest cryptography>=3.3,<3.4` (note no quotation marks), i.e. trying to write the output of `python -m pip install pytest cryptography` and the contents of a file called `3.4` to a file called `=3.3,`, and then process fails when the file `3.4` doesn't exist.

### LINKED ISSUE #92: conda run not used in subsequent tox runs
Version 0.8 has introduced that commands are run with `conda run` which is a nice improvement. However, I realized that this only happens while the conda environment is created. On subsequent tox runs when the already created environment is used, this is not anymore the case.

I created a patch which uses the `tox_runtest_pre` hook. How can I present this patch for review? Do you work with forks or directly with feature branches in this repository?

### PR DESCRIPTION
**Pull request by AntoineD**
Fixes #79 (conditional pip dependencies and isolated build too).
Fixes #92 (conda run not used with already created envs).

### CODE REVIEW

**Comment by gaborbernat** [comment]
@AntoineD shall we remove appveyor with this then?

**Comment by AntoineD** [comment]
Yes if there's no added value (I cannot find its description).

**Comment by AntoineD** [comment]
Hi @gaborbernat, would it be possible to make a new release please?

**Comment by gaborbernat** [comment]
I think you can do it, no? Just requires creating a tag here, no?

**Comment by AntoineD** [comment]
OK.

**Pull request merged**
